name: 5 Runner Parallel Test

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        slot: [1, 2, 3, 4, 5]
    runs-on: [self-hosted, macOS, ARM64]

    steps:
      - name: Print runner
        run: |
          echo "RUNNER_NAME=$RUNNER_NAME"
          echo "SLOT=${{ matrix.slot }}"
          sleep 120
